### ISSUE TITLE
Issue en línea 1.

### ISSUE THREAD

**Issue by Albert0PB** [iesgrancapitan-entornos/2023-24-pr-ctica-5-github-issues-luisperezcantarero#1]
[Issue en línea 1](https://github.com/iesgrancapitan-entornos/2023-24-pr-ctica-5-github-issues-luisperezcantarero/blob/59a20d8ac76251e92f48f5ccd94f07e21aae8bb8/fichero.py#L1)

Hay que añadirle ':' al final de la primera línea para que, valga la redundancia, la función _funcione_.

**Comment by luisperezcantarero** [comment]
¡Vaya! No me había dado cuenta, lo solucionaré de inmediato.

**Comment by luisperezcantarero** [comment]
Lo he solucionado.

**Comment by Albert0PB** [comment]
¡Extraordinario!
