### ISSUE TITLE
Issue al final de la función "suma".

### ISSUE THREAD

**Issue by Albert0PB** [iesgrancapitan-entornos/2023-24-pr-ctica-5-github-issues-luisperezcantarero#2]
[Issue en función "suma"](https://github.com/iesgrancapitan-entornos/2023-24-pr-ctica-5-github-issues-luisperezcantarero/blob/59a20d8ac76251e92f48f5ccd94f07e21aae8bb8/fichero.py#L3)

Hay que añadir una línea con "return" para que se devuelva el resultado de ejecutar la función.

**Comment by luisperezcantarero** [comment]
¡Anda pues no me había dado cuenta! Lo haré cuanto antes.
