### ISSUE TITLE
Issue al principio del código.

### ISSUE THREAD

**Issue by Albert0PB** [iesgrancapitan-entornos/2023-24-pr-ctica-5-github-issues-luisperezcantarero#3]
Escribir código mola bastante, pero no hay que olvidar la documentación. 
¿Puedes poner un comentario en bloque al comienzo del programa que explique qué es lo que hace y el nombre del autor?

**Comment by luisperezcantarero** [comment]
Está bien, lo dejaré claro para los más exigentes.
