### ISSUE TITLE
Issue relacionado con los inputs.

### ISSUE THREAD

**Issue by Albert0PB** [iesgrancapitan-entornos/2023-24-pr-ctica-5-github-issues-luisperezcantarero#4]
En tu código hay dos "inputs" en los que deberían introducirse datos numéricos. 
Sería mejor que controlases esto metiendo los inputs dentro de una función "int()" o "float()".
¿O "suma" está pensado para concatenar Strings...?

**Comment by luisperezcantarero** [comment]
Cierto, debería especificar eso para dejarlo más claro.
